---
title: "NMT-seq: dimensionality reduction using ZIFA to compare with previous data sets"
author: "Ricard Argelaguet"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
```

```{r funcs, echo=FALSE}
# scatter_theme <- function() {
#   p <- theme(
#     plot.title = element_text(size=20, hjust=0.5),
#     axis.title.y = element_text(colour="black", size=20, margin=margin(0,15,0,0)),
#     axis.title.x = element_text(colour="black", size=20, margin=margin(15,0,0,0)),
#     axis.text.x = element_text(colour="black",size=rel(1.6)),
#     axis.text.y = element_text(colour="black",size=rel(1.6)),
#     axis.line = element_line(colour="black", size=rel(0.9)),
#     axis.ticks = element_line(colour="black", size=rel(1.0)),
#     panel.background = element_blank(),
#     panel.grid = element_blank(),
#     legend.position="right",
#     legend.text=element_text(size=15),
#     legend.key = element_blank(),
#     legend.title=element_text(size=17),
#     # legend.background=element_blank()
#     # panel.border = element_blank()
#   )
# }
```


```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$expr <- "/Users/ricard/data/NMT-seq/rna/parsed/sceset_merged_all.rds"
io$metadata.file_nmt <- "/Users/ricard/data/NMT-seq/sample_info.txt"
io$metadata.file_mt <- "/Users/ricard/data/scMT/sample_info.txt"
io$outdir <- "/Users/ricard/NMT-seq/dimensionality_reduction/out"

## Define options ##
opts <- list()

# Define which cells to use
opts$nmt_cells <- fread(io$metadata.file_nmt) %>% .[pass_rnaQC==T, sample]
opts$mt_cells <- fread(io$metadata.file_mt) %>% .[pass_rnaQC==T, sample]
```

<!-- Load sample metadata -->
```{r load_metadata} 
sample_metadata_nmt <- fread(io$metadata.file_nmt) %>% .[sample %in% opts$nmt_cells] %>% .[,dataset:="This study"] %>% .[,sample:=paste0(sample,"_NMT")] %>% .[,c("pass_accQC","pass_metQC","pass_rnaQC","index"):=NULL] %>%
  .[,c("sample","culture","method","dataset")]

sample_metadata_mt <- fread(io$metadata.file_mt) %>% .[sample %in% opts$mt_cells] %>% .[,dataset:="Angermueller"] %>% .[,sample:=paste0(sample,"_Angermueller")] %>% .[,method:="MT"] %>% .[,c("pass_metQC","pass_rnaQC"):=NULL] %>%
  .[,c("sample","culture","method","dataset")]

sample_metadata <- rbind(sample_metadata_nmt, sample_metadata_mt) %>% setkey(dataset,culture)
```

```{r load_data, echo=FALSE}
sce <- readRDS(io$expr)[,sample_metadata$sample]
```


```{r filter, echo=FALSE}

# Filter genes based on dropout
opts$max.dropout <- 0.25
genes_dropout <- rownames(sce)[fData(sce)$pct_dropout<(opts$max.dropout*100)]
sce_filt <- sce[genes_dropout,]

# Filter genes based on variance
# opts$fvar <- 0.1
# genes_var <- names(tail(sort(apply(exprs(sce_filt),1,var)), n=nrow(sce_filt)*opts$fvar))
# sce_filt <- sce_filt[genes_var,]
 
# Filter genes based on biological overdispersion
# opts$fvar <- 0.5
# genes_var <- rownames(sce_filt)[tail(sort(fData(sce_filt)$bioVar, index.return=TRUE)$ix, n=nrow(sce_filt)*opts$fvar)]
# sce_filt <- sce_filt[genes_var,opts$cells]
genes_oversdispersion <- rownames(sce_filt)[fData(sce_filt)$bioVar > 0.5]
sce_filt <- sce_filt[genes_oversdispersion,]

```

<!-- Save expression matrix and run ZIFA using Python -->
```{r}
write.table(round(exprs(sce_filt),3), file = "/Users/ricard/NMT-seq/dimensionality_reduction/out/expr.csv", quote = F, sep = ",", row.names = TRUE, col.names = TRUE)
```

<!-- Load ZIFA results -->
```{r}
ZIFA <- fread("/Users/ricard/NMT-seq/dimensionality_reduction/out/output.ZIFA.txt")
ZIFA[,sample:=colnames(sce_filt)] 
ZIFA <- ZIFA %>% merge(sample_metadata,by="sample")

ZIFA[,col:=paste(paste(dataset,culture,sep="_"),method,sep="_")]
p <- ggplot(ZIFA, aes(x=V1, y=V2)) +
  geom_point(aes(color=col), size=2.5) +
  theme_bw() + 
  labs(x="ZIFA dimension 2", y="ZIFA dimension 3") +
  theme(
    axis.title.y = element_text(colour="black", size=20, margin=margin(0,5,0,0)),
    axis.title.x = element_text(colour="black", size=20, margin=margin(5,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.6)),
    axis.text.y = element_text(colour="black",size=rel(1.6)),
    axis.ticks = element_line(colour="black", size=rel(1.3)),
    legend.position="right",
    legend.text=element_text(size=10),
    legend.key = element_blank(),
    legend.title=element_text(size=15)
    # legend.background=element_blank()
    # panel.border = element_blank()
  )
print(p)


pdf("/Users/ricard/NMT-seq/dimensionality_reduction/out/ZIFA_out_12.pdf", width = 9, height = 6.5, useDingbats = F)
print(p)
dev.off()

```
