---
title: "NMT-Seq EB: Correlation between accessibility and methylation"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(weights))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(data.table))
source("/Users/ricard/NMT-seq/correlations/utils.R")
```

```{r echo=FALSE, include=FALSE}
```

<!-- # Parse and filter data -->
```{r echo=FALSE, include=FALSE}
# Data
io   <- list()
io$base_dir   <- "/Users/ricard/data/NMT-seq_EB"
io$annos_dir  <- paste0(io$base_dir, "/features/filt")
io$met_file   <- paste0(io$base_dir, "/met/parsed/met_data.tsv.gz")
io$acc_file   <- paste0(io$base_dir, "/acc/parsed/acc_data.tsv.gz")
io$in.sample_metadata <- paste0(io$base_dir,"/sample_sheet.csv")
io$outdir <- "/Users/ricard/NMT-seq/rebuttal/EB/correlations/out/metacc"

# Filtering parameters
opts <- list()
opts$met.min.weight <- 1      # minimum weight per feature (met)
opts$acc.min.weight <- 1      # minimum weight per feature (acc)
opts$min.coverage   <- 0.5    # minimum coverage per feature across samples (met/acc)
opts$fraction.sites <- 0.5    # fraction of sites (met/acc) to keep based on variance
# opts$min.n          <- 100    # minimum number of features per annotation
opts$min.s          <- 15     # minimum number of samples to do the correlation
opts$n_perms        <- 100    # Number of random permutations
opts$threshold_fdr  <- 0.10   # pvalue threshold for significance in FDR
opts$method <- "pearson"      # correlation type
opts$weight <- TRUE           # weighted correlation?

opts$cor_samples <- T
opts$permutation <- T

# Define which annotations to use and the order for plotting
# opts$met_annos <- c("prom_2000_2000_cgi","prom_2000_2000_noncgi","exons","introns","active_enhancers","super_enhancers","primed_enhancers","CTCF","Nanog","Oct4","IAP","p300","DHS","CGI")
# opts$acc_annos <- c("prom_2000_2000_cgi","prom_2000_2000_noncgi","exons","introns","active_enhancers","super_enhancers","primed_enhancers","CTCF","Nanog","Oct4","IAP","p300","DHS","CGI")
opts$met_annos <- c("prom_2000_2000", "super_enhancers", "CTCF","genebody","p300","Oct4","Nanog")
opts$acc_annos <- c("prom_2000_2000", "super_enhancers", "CTCF","genebody","p300","Oct4","Nanog")

opts$anno_names <- c(
  "prom_2000_2000_cgi"="CGI promoters",
  "prom_2000_2000_noncgi"="non-CGI promoters",
  "prom_2000_2000_cgi"="CGI promoters",
  "prom_2000_2000_noncgi"="non-CGI promoters",
  "active_enhancers"="Active enhancers",
  "super_enhancers"="Super enhancers",
  "primed_enhancers"="Primed enhancers",
  "exons"="Exons",
  "introns"="Introns"
)

# cells 
opts$cells <- fread(io$in.sample_metadata, header=T) %>% .[pass_metQC==T & pass_accQC==T,sample]
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$in.sample_metadata, header=T) %>% .[sample%in%opts$cells]
```

<!-- Load methylation and accessibility data -->
```{r load_data, echo=FALSE, include=FALSE}

# Load methylation data
met <- fread(sprintf("zcat < %s", io$met_file)) %>% as.data.table %>% 
  .[anno%in%opts$met_annos & sample%in%opts$cells] %>% .[,anno:=factor(anno, levels=opts$met_annos)] %>%
  .[,anno:=stringr::str_replace_all(anno, opts$anno_names)]

# Load accessibility data
acc <- fread(sprintf("zcat < %s", io$acc_file)) %>% as.data.table %>% 
  .[anno%in%opts$acc_annos & sample%in%opts$cells] %>% 
  .[,anno:=factor(anno, levels=opts$acc_annos)] %>% .[,anno:=stringr::str_replace_all(anno, opts$anno_names)]

# Combine the two data sets
metacc <- merge(
  met[,c("sample", "id", "anno", "rate", "weight")] %>% setnames(c("rate", "weight"), c("met_rate", "met_weight")),
  acc[,c("sample", "id", "anno", "rate", "weight")] %>% setnames(c("rate", "weight"), c("acc_rate", "acc_weight")),
  by=c("sample", "id", "anno")
)
# rm(met, acc)

```

<!-- Parse and filter data -->
```{r filter, echo=FALSE}

if (opts$cor_samples) {
  
  # Intersect the two data sets
  metacc <- merge(met[,c("sample", "id", "anno", "rate", "weight")] %>% setnames(c("rate", "weight"), c("met_rate", "met_weight")),
                  acc[,c("sample", "id", "anno", "rate", "weight")] %>% setnames(c("rate", "weight"), c("acc_rate", "acc_weight")),
                  by=c("sample", "id", "anno"))
  rm(met, acc)
  ## Remove features with low weight (all types of correlation)
  metacc <- metacc[met_weight >= opts$met.min.weight & acc_weight >= opts$acc.min.weight]
  # To correlate across samples
  metacc_filt <- copy(metacc)
  
  ## Filter sites with low coverage
  nsamples <- length(unique(metacc$sample))
  metacc_filt <- metacc_filt[, cov := .N / nsamples, by = c("id", "anno")] %>% .[cov >= opts$min.coverage] %>% .[, cov := NULL]
  metacc <- metacc[, cov := .N / nsamples, by = c("id", "anno")] %>% .[cov >= opts$min.coverage] %>% .[, cov := NULL]
  
  
  ## Remove constant sites and filter based on variability (separately for each feature)
  keep_hv_sites <- metacc_filt %>% split(.$anno) %>% map(~ .[,.(met_var = wtd.var(met_rate, met_weight), acc_var = wtd.var(acc_rate, acc_weight)), by = c("id")] %>% .[met_var > 2 | acc_var > 2] %>% .[, var := acc_var * met_var] %>% setorder(-var)  %>% head(n = nrow(.) * opts$fraction.sites) %>% .$id)
  metacc_filt <- metacc_filt %>% split(.$anno) %>% map2(.,names(.), function(x,y) x[id %in% keep_hv_sites[[y]]]) %>% rbindlist
  
  ## Filter id pairs with small number of samples to do the correlation
  metacc_filt <- metacc_filt[,n:=.N, by=c("id","anno")] %>% .[n >= opts$min.s] %>% .[,n:=NULL]
}
```

<!-- Compute correlations  -->
```{r cor_rate, echo=FALSE, include=FALSE}
# Weighted correlation
if (opts$weight == TRUE){
  if (opts$method != "pearson") { print("Weighted correlation only supported for pearson"); stop() }
  if (opts$cor_samples) {
    # Correlate rate across samples
    cor_samples <- metacc_filt[, wtd.cor(met_rate, acc_rate, met_weight)[, c("correlation", "t.value", "p.value")], by = c("id", "anno")]
  }
  # Correlate rate across genes
  cor_features <- metacc[, wtd.cor(met_rate, acc_rate, met_weight)[, c("correlation", "t.value", "p.value")], by = c("sample", "anno")]
}else{
  if (opts$cor_samples) {
    # Correlate rate across samples
    cor_samples <- metacc_filt[, .(V1 = unlist(cor.test(met_rate, acc_rate, alternative = "two.sided", method = opts$method)[c("estimate", "statistic", "p.value")])), by = c("id", "anno")]
  }
  # Correlate rate across genes
  cor_features <- metacc[, .(V1 = unlist(cor.test(met_rate, acc_rate, alternative = "two.sided", method = opts$method)[c("estimate", "statistic", "p.value")])), by = c("sample", "anno")]
}

# Compute adjusted p-values across samples (both FDR and Bonferroni)
if (opts$cor_samples) {
  cor_samples <- cor_samples %>% .[, para := c("r", "t", "p")] %>% dcast(id + anno ~ para, value.var = "V1") %>%
        .[, c("padj_fdr", "padj_bonf") := list(p.adjust(p, method = "fdr"), p.adjust(p, method = "bonferroni")), by = anno] %>%
        .[, c("log_padj_fdr","log_padj_bonf") := list(-log10(padj_fdr), -log10(padj_bonf))] %>%
        .[, sig := padj_fdr <= opts$threshold_fdr] %>%  setorder(padj_fdr)
}
  

# Compute adjusted p-values across genes (both FDR and Bonferroni)
cor_features <- cor_features %>% .[,para := c("r", "t", "p")] %>% dcast(sample + anno ~ para, value.var = "V1") %>% 
      .[, c("padj_fdr", "padj_bonf") := list(p.adjust(p, method = "fdr"), p.adjust(p, method = "bonferroni")), by = anno] %>%
      .[, c("log_padj_fdr", "log_padj_bonf") := list(-log10(padj_fdr), -log10(padj_bonf))] %>%
      .[, sig := padj_fdr <= opts$threshold_fdr] %>% setorder(padj_fdr)
```


<!-- Run permutation test for correlations  -->
```{r perm_cor_rate, echo=FALSE, include=FALSE}
if (opts$cor_samples & opts$permutation) {
  pp_vals <- vector(mode = "numeric", length = length(cor_samples$p))
  for (k in 1:opts$n_perms){
    # Copy original data
    metacc_filt_perm <- copy(metacc_filt)
    # Permute accessibility rates
    metacc_filt_perm <- metacc_filt_perm[, acc_rate := sample(acc_rate), by = c("id", "anno")]
    # Compute correlation across samples
    # cor_samples_perm <- metacc_filt_perm[, .(p = wtd.cor(met_rate, acc_rate, met_weight)[, c("p.value")]), by = c("id", "anno")]
    cor_samples_perm <- metacc_filt_perm[, .(p = cor.test(met_rate, acc_rate, method=opts$method)[["p.value"]]), by = c("id","anno")]
    # For each annotation sort by p-value
    cor_samples_perm <- cor_samples_perm %>% split(.$anno) %>% map(~ .[,.(anno = anno, p = sort(p))]) %>% rbindlist
    # Add the sorted p-values
    pp_vals <- pp_vals + cor_samples_perm %>% .[, p]
  }
  # Compute the average p-values
  pp_vals <- pp_vals / opts$n_perms
  # Store them in a data.table for later analysis
  cor_samples_perm <- cor_samples_perm[, p := pp_vals]
}
```

<!-- Rename annotations -->
```{r rename, echo=FALSE, include=FALSE}
# if (opts$cor_samples) {
#   cor_samples$anno <- stringr::str_replace_all(cor_samples$anno, opts$anno_names)
#   if (opts$permutation)
#     cor_samples_perm$anno <- stringr::str_replace_all(cor_samples_perm$anno, opts$anno_names)
# }
# cor_features$anno <- stringr::str_replace_all(cor_features$anno, opts$anno_names)
```

<!-- Boxplot of correlations between accessibility and methylation -->
```{r boxplot_expr, echo=FALSE, warning=FALSE, include=TRUE}

# Boxplot of correlations across samples
if (opts$cor_samples) {
  p <- ggplot(cor_samples[,c("anno","r")], aes(x=anno, y=r, fill=anno)) +
    geom_boxplot(alpha=0.8, outlier.shape=NA, fill="yellowgreen") + geom_hline(yintercept=0, colour="black", linetype="dashed") +
    labs(title="Correlation across cells", x="", y="Weighted Pearson correlation coefficient") +
    coord_flip() + boxplot_theme()
  # print(p)
  # pdf(file=paste0(io$outdir, "/metacc_boxplot_acrosssamples.pdf"), width=8, height=6)
  # print(p)
  # dev.off()
  
}

# Boxplot of correlations across genes
p <- ggplot(cor_features[,c("anno","r")], aes(x=anno, y=r, fill=anno)) +
  geom_boxplot(alpha=0.8, outlier.shape=NA, fill="yellowgreen") + 
  geom_hline(yintercept=0, colour="black", linetype="dashed") +
  labs(title="Correlation across genes", x="", y="Pearson correlation coefficient") +
  coord_flip() + boxplot_theme()
# print(p)
# pdf(file=paste0(io$outdir, "/metacc_boxplot_acrossfeatures.pdf"), width=8, height=6)
# print(p)
# dev.off()

# Boxplot of correlations across genes by lineage
tmp <- merge(cor_features, sample_metadata[,c("sample","lineage")], by="sample")
p <- ggplot(tmp, aes(x=anno, y=r)) +
  # geom_boxplot(alpha=0.8, outlier.shape=NA, fill="#F8766D") +
  geom_boxplot(aes(fill=lineage), alpha=0.8, outlier.shape=NA) +
  scale_fill_manual(values=c("green4","green3")) +
  geom_hline(yintercept=0, colour="black", linetype="dashed") +
  labs(title="Correlation across genes", x="", y="Pearson correlation coefficient") +
  # scale_y_continuous(limits=c(-0.41, 0.05)) +
  coord_flip() + boxplot_theme()
# print(p)

# pdf(file=paste0(io$outdir, "/metacc_boxplot_acrossfeatures_lineage.pdf"), width=8, height=6)
# print(p)
# dev.off()
```


 <!-- Volcano plot of p-values against Pearson's r and QQ-plot of p-values -->
```{r corplot, messages=FALSE, echo=FALSE, include=TRUE, warning=FALSE, fig.height=6.5, fig.width=16}

if (opts$cor_samples & opts$permutation) {
  # load("out/cor.RData")
  pp = qq <- list()
  for (n in unique(cor_samples$anno)) {
    
    # Compute positive and negative hits in terms of correlation
    negative_hits <- cor_samples[anno==n & sig==TRUE & r<0,id]
    positive_hits <- cor_samples[anno==n & sig==TRUE & r>0,id]
    all <- nrow(cor_samples[anno == n,])
    
    # Create volcano plot
    pp[[n]] <- gg_volcano_plot(cor_samples[anno == n,], title = "")
    
    # Crete qqplot
    qq[[n]] <- gg_qqplot(cor_samples[anno == n, ], cor_samples_perm[anno == n]$p, title = "")
    
    # Plot and save
    # print(plot_grid(pp[[n]], qq[[n]], labels = c("", ""), label_size = 20, ncol = 2, nrow = 1))
    pdf(file=paste0(io$outdir,"/metacc_cor_", n, ".pdf"), width = 14, height = 8, useDingbats = FALSE)
    grid.arrange(pp[[n]], qq[[n]], ncol=2, top = textGrob(n, gp=gpar(fontsize=29, fontface = "bold")), newpage = TRUE)
    dev.off()
  }
}
```

<!-- <!-- Scatterplot of correlations between methylation and accessibility across features --> -->
<!-- ```{r scatterplots, echo=FALSE, include=FALSE} -->

<!-- a <- "p300" -->
<!-- # samples <- c("Plate1_E05","Plate1_F01","Plate2_F02","Plate1_H09") -->
<!-- samples <- c("Plate1_E05","Plate1_F01","Plate1_F07","Plate1_D01") -->

<!-- # Load pseudotime statistics and merge with data -->
<!-- pseudotime <- fread("/Users/ricard/NMT-seq/rebuttal/EB/pseudotime/out/destiny.tsv", header=T ) -->
<!-- tmp <- metacc[,met_group:=cut(met_rate, breaks=c(-1,25,50,75,101))] %>% merge(pseudotime,by="sample") %>% -->
<!-- # tmp <- metacc[,met_group:=cut(met_rate, breaks=c(-1,10,30,45,60,75,90,101))] %>% merge(pseudotime,by="sample") %>% -->
<!--   .[,sample:=factor(sample,levels=samples)] -->

<!-- # p <- ggplot(tmp[sample%in%samples & anno==a], aes(x=met_rate,y=acc_rate)) + -->
<!-- #   geom_point(aes(color=pseudotime), alpha=0.5) + -->
<!-- #   stat_smooth(method="lm", color="black", alpha=0.5, size=1.5) + -->
<!-- #   facet_wrap(~sample, nrow=2, ncol=2, scales="fixed") + -->
<!-- #   scale_color_gradient2() + -->
<!-- #   xlab("Methylation rate") + ylab("Accessibility rate") + -->
<!-- #   theme( -->
<!-- #   plot.title = element_text(size=30, hjust=0.5, margin=margin(0,0,20,0)), -->
<!-- #   axis.title.y = element_text(colour="black", size=28, vjust=1.5), -->
<!-- #   axis.title.x = element_text(colour="black", size=28, vjust=1.5, margin=margin(15,0,0,0)), -->
<!-- #   axis.text.x = element_text(colour="black",size=rel(1.8)), -->
<!-- #   axis.text.y = element_text(colour="black",size=rel(1.8)), -->
<!-- #   # axis.line = element_line(colour="black", size=rel(0.7)), -->
<!-- #   # axis.ticks.x = element_line(colour="black", size=rel(0.8)), -->
<!-- #   # axis.ticks.y = element_blank(), -->
<!-- #   legend.position="top", -->
<!-- #   panel.background = element_blank(), -->
<!-- #   panel.border = element_blank(), -->
<!-- #   panel.grid = element_blank() -->
<!-- # ) -->
<!-- # print(p) -->

<!-- p <- ggplot(tmp[sample%in%samples & anno==a], aes(x=met_group,y=acc_rate)) + -->
<!--   geom_boxplot(aes(fill=pseudotime), alpha=0.8) + -->
<!--   geom_smooth(method = "lm", se=T, aes(group=1), size=1.0, color="darkgrey") + -->
<!--   scale_fill_gradient2() + -->
<!--   # scale_color_gradientn(colors=terrain.colors(10)) + -->
<!--   facet_wrap(~sample, nrow=2, ncol=2, scales="fixed") + -->
<!--   xlab("Methylation rate") + ylab("Accessibility rate") + -->
<!--   theme_bw() + -->
<!--   theme( -->
<!--   plot.title = element_text(size=30, hjust=0.5, margin=margin(0,0,20,0)), -->
<!--   axis.title.y = element_text(colour="black", size=16, vjust=1.5), -->
<!--   axis.title.x = element_text(colour="black", size=16, vjust=1.5, margin=margin(15,0,0,0)), -->
<!--   axis.text.x = element_text(colour="black",size=rel(1.3)), -->
<!--   axis.text.y = element_text(colour="black",size=rel(1.3)), -->
<!--   legend.position="top", -->
<!--   panel.background = element_blank(), -->
<!--   panel.grid.major = element_line(colour = "grey92"), -->
<!--   panel.grid.minor = element_blank() -->
<!-- ) -->
<!-- # print(p) -->
<!-- pdf(file=paste0(io$outdir, "/metacc_scatterplot_",a,".pdf"), width=5.5, height=4, useDingbats = F) -->
<!-- print(p) -->
<!-- dev.off() -->
<!-- ``` -->


<!-- <!-- Save results --> -->
<!-- ```{r} -->
<!-- cols <- c("p","r","t","padj_fdr","padj_bonf","log_padj_fdr","log_padj_bonf") -->

<!-- cor_features[,(cols) := round(.SD,3), .SDcols=cols] -->
<!-- fwrite(cor_features, paste0(io$outdir,"/metacc_cor_features.tsv"), sep="\t") -->

<!-- if (opts$cor_samples) { -->
<!--   cor_samples[,(cols) := round(.SD,3), .SDcols=cols] -->
<!--   fwrite(cor_samples, paste0(io$outdir,"/metacc_cor_samples.tsv"), sep="\t") -->

<!--   if (opts$permutation) { -->
<!--     cor_samples_perm[,(cols) := round(.SD,3), .SDcols=cols] -->
<!--     fwrite(cor_samples_perm, paste0(io$outdir,"/metacc_cor_samples_perm.tsv"), sep="\t") -->
<!--   } -->
<!-- } -->
<!-- ``` -->

<!-- Save results -->
```{r}
fwrite(round_df(cor_features,5), paste0(io$outdir,"/metacc_cor_loci.tsv"), sep="\t")
if (opts$cor_samples) {
  fwrite(round_df(cor_samples,5), paste0(io$outdir,"/metacc_cor_samples.tsv"), sep="\t")
  # if (opts$permutation) {
  #   fwrite(round_df(cor_samples_perm,5), paste0(io$outdir,"/metrna_cor_samples_perm.tsv"), sep="\t")
  # }
}
```
