---
title: "NMT-Seq: Example genes with clustered profiles"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
# devtools::install_github("andreaskapou/BPRMeth-devel")
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(BPRMeth))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(stringi))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(cowplot))
```

```{r echo=FALSE, include=FALSE}
ggplot_bpr_profiles <- function(X, obs, title="", subtitle="", up_label="-500bp", down_label="+500bp", middle_label="TSS", ...){
  # ggplot(X, aes(x = xs, y = ys)) +
  p <- ggplot(data = data.frame(X), aes(x = xs, y = ys)) +
    geom_line(aes(x = xs, y = ys), size=1.5, col = "darkblue") +
    geom_point(data = obs, mapping = aes(x = x, y = y), shape=1, color="red", size=3) +
    geom_ribbon(data = data.frame(X), mapping = aes(ymin= ys_low, ymax= ys_high), alpha=0.4, size = 0.1, fill="cornflowerblue") +
    scale_x_continuous(limits = c(-1, 1), labels =c(up_label, "", middle_label, "", down_label)) + 
    scale_y_continuous(limits = c(0, 1), breaks=pretty_breaks(n=4)) + 
    labs(title = title, subtitle = subtitle, x="genomic region", y="Accessibility") + 
    line_theme()# + theme(axis.text.x = element_blank())
}

# Define ggplot2 theme for line plots
line_theme <- function(){
  p <- theme(
      plot.title=element_text(size=20, face='bold', margin=margin(0,0,3,0), hjust=0.5),
      #plot.subtitle=element_text(size=15, margin=margin(0,0,4,0), hjust=0.5),
      axis.text=element_text(size=rel(1.05), color='black'),
      axis.title=element_text(size=rel(1.45), color='black'),
      axis.title.y = element_text(margin=margin(0,10,0,0)),
      axis.title.x = element_text(margin=margin(10,0,0,0)),
      axis.ticks.x = element_line(colour="black", size=rel(0.8)),
      axis.ticks.y = element_blank(),
      legend.position="right",
      legend.key.size = unit(1.9, 'lines'),
      legend.title=element_text(size=24, face='bold'),
      legend.text=element_text(size=19),
      panel.border=element_blank(),
      panel.grid.major = element_line(colour = "gainsboro"),
      #panel.grid.minor = element_line(colour = "grey"),
      panel.background = element_blank()
    )
}
```

<!-- # Parse and filter data -->
```{r echo=FALSE, include=FALSE}
# Data
set.seed(12345)
io                     <- list()
io$base_dir            <- "/home/cakapourani/Documents/Code/datasets/nmt-seq-data-eb"
load(paste0(io$base_dir,"/acc/parsed/profiles/acc_400bp.RData"))
io$base_dir            <- "/home/cakapourani/Documents/Code/datasets/nmt-seq-data-eb"
io$out_dir             <- "/home/cakapourani/Documents/Code/nmt-seq/rebuttal/EB/acc_conservation/out/examples/low_heter_high_expr/"
io$rna_file            <- paste0(io$base_dir, "/rna/parsed/sceset.rds")
io$acc_file            <- paste0(io$base_dir, "/acc/parsed/profiles/cons_cluster_prom_200_200_basis13_GpCcov8_bic0.1_cellcov0.6.rds")

opts                   <- list(basis_prof = create_rbf_object(M = 13))
```

<!-- # Load scRNA data -->
```{r load_rna, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
sceset       <- readRDS(file = io$rna_file)  # Load expression as SCESet object
# sceset       <- filter(sceset, culture=="Serum" & type=="NMT") # Remove non-interesting cells
# Create data.table
rna_dt       <- exprs(sceset) %>% t %>% as.data.table(keep.rownames = "sample") %>% melt(id.vars = "sample", value.name = "expr", variable.name = "gene")
# Compute summary statistics for each gene across cells
rna_all_st   <- rna_dt[, .(mean_expr = mean(expr), median_expr = median(expr), var_expr = var(expr), sd_expr = sd(expr), cv_expr = sd(expr)/mean(expr)), by = gene]
N_cells      <- length(unique(rna_dt$sample))  # Number of unique cells
rna_all_st   <- rna_all_st[, cv_expr := log2((1 + 1/(4 * N_cells)) * cv_expr)]  # Correct CV empirically

# Extract gene coordinates metadata to do the overlap
rna_metadata <- fData(sceset) %>% tibble::rownames_to_column("gene") %>% as.data.table %>% .[,c("chr", "start", "end", "gene", "ens_id")]  %>% .[, chr := as.factor(sub("chr", "", chr))] %>% setnames("ens_id", "id")

rna_all_st   <- merge(rna_metadata[, c("chr", "id", "gene")], rna_all_st, by = c("gene")) # Merge using all samples
rna_dt       <- merge(rna_metadata[, c("chr", "id", "gene")], rna_dt, by = c("gene"))     # Merge using only samples that pass filtering
rm(sceset, rna_metadata)
```

<!-- # Load sc-NOMe-seq data -->
```{r load_acc, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
accrna_dt  <- readRDS(io$acc_file) %>% .[cells > 5] # Load accessibility data
accrna_all <- merge(rna_all_st, accrna_dt, by = c("id")) %>% setorder(clusters) # Merge with expression data using all samples 

accrna_all_factor <- copy(accrna_all) # Copy acc_data object
accrna_all_factor <- accrna_all_factor %>% .[, clusters := factor(clusters)] %>% .[, N := .N, by = clusters] %>% .[N > 5] # Make clusters as factors
```

# Specific gene examples
```{r plur_genelist, echo=FALSE, warning=FALSE, message=FALSE}
## gene_examples <- c(2, 824, 1005, 1016, 1166, 1172, 1174, 1662, 2104, 2102, 2133, 2471)
gene_examples <- c("ENSMUSG00000000399", "ENSMUSG00000037552", "ENSMUSG00000033233", "ENSMUSG00000008601", "ENSMUSG00000028786", "ENSMUSG00000028848")# , "ENSMUSG00000028865")# , "ENSMUSG00000028978")
gene_examples <- "ENSMUSG00000021255"

accrna_all_factor <- setorderv(accrna_all_factor, c("clusters", "mean_expr"), order = c(1,-1))
gene_examples <- accrna_all_factor$id[11:20]

# gene_examples <- "ENSMUSG00000037552"
my_counter <- 11
for (gene_id in gene_examples){
  gene_ind <- which(accrna_all_factor$id == gene_id)         # Get gene ENS id
  gene_dt <- lapply(region_dt, "[[", gene_id)                # Extract accessibility data
  cl_names <- accrna_all_factor$cell_names[[gene_ind]]       # Names of cells passed filtering
  cl_assign <- accrna_all_factor$cell_clusters[[gene_ind]]   # Cluster assignment of cells
  cl_profiles <- accrna_all_factor$cell_profiles[[gene_ind]] # Learned profiles for each cluster
  K <- NCOL(cl_profiles)                                     # Number of clusters K
  xs <- seq(-1, 1, length = 100)
  ys <- matrix(0, ncol = K, nrow = length(xs))
  labs <- vector("character", length = K)
  for (k in 1:K){   # Iterate over each cluster
    ys[,k] <- eval_probit_function(opts$basis_prof, xs, cl_profiles[, k]) # Evaluate function for plotting
    nnn <- cl_names[which(cl_assign == k)]                                # Get names of cells belonging to each cluster
    labs[k] <- paste0("C", k)#, " ", round(mean(rna_dt[id == accrna_all_factor$id[gene_ind] & sample %in% nnn]$expr), 2))
  }
  # Create a data.table object
  dt2 <- data.table(ys) %>% setnames(labs) %>% melt(variable.name = "Cluster", value.name = "ys") %>% .[, xs := xs]
  # Create plot of clusters
  p_cl_prof <- ggplot(dt2, aes(x = xs, y = ys, color=Cluster)) + geom_line(size=2) +
      scale_x_continuous(limits = c(-1, 1), labels =c("-200bp", "", "TSS", "", "+200bp")) + 
      scale_y_continuous(limits = c(0, 1), breaks=pretty_breaks(n=4)) + 
      scale_color_brewer(palette="Dark2") + scale_fill_brewer(palette="Dark2") +
      labs(title = paste0("Gene ", accrna_all_factor$gene[gene_ind]), x="genomic region", y="Accessibility") + line_theme()
  
  # Create subdirectories for each gene
  io$out_dir_loc <- paste0(io$out_dir, my_counter, "_", gene_id, "/")
  ifelse(!dir.exists(file.path(io$out_dir_loc)), dir.create(file.path(io$out_dir_loc)), FALSE)
  
  cluster_plots <- list()
  for (k in 1:K){
    gene_dt_filt <- gene_dt[cl_names[which(cl_assign == k)]]
    cells_names <- names(gene_dt_filt)
    cl_pop <- length(cells_names)  # Number of cells in cluster k
    if (cl_pop > 30){ cl_pop <- 30 } # Keep only first 8 cells for plotting
    # Learn profiles for each cell
    prof_cells <- bpr_bayes(x = gene_dt_filt[1:cl_pop], basis = opts$basis_prof, gibbs_nsim = 3000, 
                            gibbs_burn_in = 1000, is_parallel = FALSE, keep_gibbs_draws = TRUE)
    H <- design_matrix(x = opts$basis_prof, obs = xs)$H  # Create design matrix
    ys_draws <- matrix(0, nrow = NROW(prof_cells$W_draws[[1]]), ncol = length(xs))
    dt <- data.table(xs = xs, ys = 0, ys_low = 0, ys_high = 0)
    pp <- list()
    for (m in 1:cl_pop){
      w_draws <- prof_cells$W_draws[[m]] # Compute predictive distribution
      for (i in 1:NROW(prof_cells$W_draws[[1]])){ ys_draws[i, ] <- pnorm(H %*% w_draws[i, ]) }
      # Compute quantiles of ys
      ys_q <- apply(ys_draws, 2, quantile, probs = c(0.1, 0.9),  na.rm = TRUE)
      dt <- dt %>% .[, c("ys", "ys_low", "ys_high") := list(colMeans(ys_draws), ys_q[1, ], ys_q[2, ])]
      obs <- as.data.table(gene_dt_filt[[m]]) %>% setnames(c("x", "y"))
      pp[[m]] <- ggplot_bpr_profiles(X = dt, obs = obs, title = paste0("Cell ", cells_names[m]), subtitle = paste0("Expr = ", round(rna_dt[id == gene_id & sample == cells_names[m], expr], 3)),  up_label = "-200bp", down_label = "+200bp", middle_label = "TSS") ##subtitle = paste0("Expr = ", round(rna_dt[id == gene_id & sample == cells_names[m], expr], 3))
      
      pdf(file = paste0(io$out_dir_loc, "c_", k, "_cell_", cells_names[m], "_prof_", gene_id, ".pdf"), width = 6, height = 4, useDingbats = FALSE)
      print(pp[[m]])
      dev.off()
    }
    cluster_plots[[k]] <- cowplot::plot_grid(plotlist = pp, label_size = 30, ncol = 2, nrow = 4, rel_widths = c(1, 1.2))
  }
  
  pdf(file = paste0(io$out_dir_loc, "cl_profiles_", gene_id, ".pdf"), width = 6, height = 4, useDingbats = FALSE)
  print(p_cl_prof)
  dev.off()
  my_counter <- my_counter + 1
  # 
  # 
  # for (k in 1:K){
  #   pdf(file = paste0(io$out_dir, "gene_cl_profiles_", gene_id, "_cells_cl_", k, ".pdf"), width = 13, height = 14)
  #   print(cluster_plots[[k]])
  #   dev.off()
  # }
}

```

