---
title: "NMT-seq serum cells: pseudotime estimation using destiny"
author: "Ricard Argelaguet"
output: 
  BiocStyle::html_document: 
  fig_width: 10
fig_height: 8
---


```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
library(destiny)
```

```{r}
## I/O ##
io <- list()
io$basedir <- "/Users/ricard/data/NMT-seq"
io$in.sample_metadata <- paste0(io$basedir,"/sample_info.txt")
io$rna.infile <- paste(io$basedir,"rna/parsed/sceset.rds",sep="/")

## Options ##
opts <- list()
opts$cells <- fread(io$in.sample_metadata, header=T) %>% .[pass_rnaQC==T,sample]
```

<!-- Load sample metadata -->
```{r}
metadata <- fread(io$in.sample_metadata, header=T) %>% .[sample%in%opts$cells]
```

<!-- Load expression data -->
```{r load_data, echo=FALSE}
sce <- readRDS(io$rna.infile) 

# Filter cells that did not pass QC
sce <- sce[,opts$cells]

# Keep N more variable or overdispersed genes
N <- 500
# genes <- names(tail(sort(apply(exprs(sce),1,var)), n=N))
genes <- rownames(head(fData(sce)[order(fData(sce)$bioVar, decreasing = T),],n=N))
sce <- sce[rownames(sce) %in% genes]
```


```{r}

dm <- DiffusionMap(t(exprs(sce)))
# plot(dm, col.by = 'variable')

plot(
    eigenvectors(dm)[,1],
    eigenvectors(dm)[,2],
    xlab="Diffusion component 1",
    ylab="Diffusion component 2",
    col = c("red","green")[as.numeric(factor(sce$lineage))],
    pch = c(16,17)[as.numeric(factor(sce$lineage))]
)


tmp <- data.frame(
  sample = colnames(sce),
  culture = sce$culture,
  x = eigenvectors(dm)[,1],
  y = eigenvectors(dm)[,2]
)


p <- ggplot(tmp, aes(x,y)) +
  geom_point(aes(color=culture), alpha=0.7, size=2.0) +
  labs(x="Diffusion component 1", y="Diffusion component 2") +
  theme(
    plot.title = element_text(size=20, hjust=0.5),
    axis.title.y = element_text(colour="black", size=16, margin=margin(0,15,0,0)),
    axis.title.x = element_text(colour="black", size=16, margin=margin(15,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.4)),
    axis.text.y = element_text(colour="black",size=rel(1.4)),
    axis.line = element_line(colour="black", size=rel(0.9)),
    axis.ticks = element_line(colour="black", size=rel(1.0)),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.position="top",
    legend.text=element_text(size=15),
    legend.key = element_blank(),
    legend.title=element_blank(),
    legend.background=element_blank(),
    panel.border = element_blank()
  )
print(p)

# pdf("/Users/ricard/NMT-seq/rebuttal/2i_vs_serum/pseudotime/out/pseudotime.pdf", useDingbats = F)
# print(p)
# dev.off()
```


```{r}
tmp <- data.frame(sample=colnames(sce), pseudotime=dm$DC1)
write.table(tmp, "/Users/ricard/NMT-seq/pseudotime/out/destiny.tsv", quote=F, sep="\t", row.names = F, col.names = T)
```

