---
title: "NMT-seq serum cells: heatmap of expression data"
author: "Ricard Argelaguet"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
```

```{r funcs, echo=FALSE}
matrix.please<-function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}
```


```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$expr <- "/Users/ricard/data/NMT-seq/rna/parsed/sceset.rds"
io$metadata.file <- "/Users/ricard/data/NMT-seq/sample_info.txt"
io$outdir <- "/Users/ricard/NMT-seq/heatmap/out"

## Define options ##
opts <- list()

# Define which cells to use
opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T, sample]
```

```{r load_data, echo=FALSE}

# Load sample metadata
sample_metadata <- fread(io$metadata.file) %>% .[sample %in% opts$cells]

# Load expression data and convert to data.table
sce <- readRDS(io$expr)
```


```{r filter, echo=FALSE}

# Filter genes based on dropout
opts$max.dropout <- 0.25
genes_dropout <- rownames(sce)[fData(sce)$pct_dropout<(opts$max.dropout*100)]
sce_filt <- sce[genes_dropout,opts$cells]

# Filter genes based on variance
# opts$fvar <- 0.5
# genes_var <- names(tail(sort(apply(exprs(sce_filt),1,var)), n=nrow(sce_filt)*opts$fvar))
# sce_filt <- sce_filt[genes_var,opts$cells]
 
# Filter genes based on biological overdispersion
# opts$fvar <- 0.5
# genes_var <- rownames(sce_filt)[tail(sort(fData(sce_filt)$bioVar, index.return=TRUE)$ix, n=nrow(sce_filt)*opts$fvar)]
# sce_filt <- sce_filt[genes_var,opts$cells]
genes_oversdispersion <- rownames(sce_filt)[fData(sce_filt)$bioVar > 2]
sce_filt <- sce_filt[genes_oversdispersion,opts$cells]

```

<!-- ```{r convert2matrix, echo=FALSE} -->
<!-- rna_matrix <- rna[,c("sample","gene","expr")] %>% dcast(sample~gene, value.var="expr") %>% matrix.please -->
<!-- ``` -->

# Unsupervised
```{r unsupervised_heatmap, echo=FALSE}

annotation_row <- data.frame(
  row.names = sample_metadata$sample,
  method = sample_metadata$method
)

pdf(paste0(io$outdir,"/heatmap_rna_unsupervised.pdf"), width = 6.5, height = 4.5)
pheatmap::pheatmap(t(exprs(sce_filt)),
                   cluster_rows = T, cluster_cols = T, annotation_row = annotation_row, annotation_col = NA,
                   show_colnames = F, show_rownames = F)
dev.off()
```

# Supervised

## Marker genes
```{r load_genes, echo=FALSE}
pluri <- fread("/Users/ricard/NMT-seq/genesets/pluripotency.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
diff <- fread("/Users/ricard/NMT-seq/genesets/differentiation.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
housek <- fread("/Users/ricard/NMT-seq/genesets/housekeeping.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
```

### Heatmap
```{r supervised_heatmap, echo=FALSE, include=TRUE}

feature_df <- data.frame(gene=c(pluri,diff,housek), class=c(rep("Pluripotency",length(pluri)),rep("Differentiation",length(diff)),rep("Housekeeping",length(housek)))) %>% tibble::column_to_rownames("gene")
sample_df <- data.frame(sample=colnames(sce), method=sce$method) %>% tibble::column_to_rownames("sample")

# annotation_colors	<- list(culture=c("red","green"), method=c("blue","orange"), )

pdf(paste0(io$outdir,"/heatmap_rna_supervised.pdf"), width = 6.5, height = 4.5)
pheatmap::pheatmap(t(exprs(sce)[rownames(feature_df),]), border_color="black", main="",
         cluster_cols=F, cluster_rows=T, show_rownames=FALSE, show_colnames=FALSE,
         annotation_row=sample_df, annotation_col=feature_df, annotation_colors=NA,
         legend=TRUE, annotation_legend=TRUE, legend_labels=NA,
         annotation_names_col=F, fontsize=13)
dev.off()
```