---
title: "NMT-seq EB: dimensionality reduction on expression data"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
```

```{r funcs, echo=FALSE}
matrix.please<-function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}

scatter_theme <- function() {
  p <- theme(
    plot.title = element_text(size=20, hjust=0.5),
    axis.title.y = element_text(colour="black", size=20, margin=margin(0,15,0,0)),
    axis.title.x = element_text(colour="black", size=20, margin=margin(15,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.6)),
    axis.text.y = element_text(colour="black",size=rel(1.6)),
    axis.line = element_line(colour="black", size=rel(0.9)),
    axis.ticks = element_line(colour="black", size=rel(1.0)),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.position="right",
    legend.text=element_text(size=15),
    legend.key = element_blank(),
    legend.title=element_text(size=17),
    legend.background=element_blank(),
    panel.border = element_blank()
  )
}
```

<!-- Define I/O and options -->
```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$expr <- "/Users/ricard/data/NMT-seq_EB/rna/parsed/sceset.rds"
# io$metadata.file <- "/Users/ricard/data/NMT-seq_EB/sample_sheet_rna.csv"
io$metadata.file <- "/Users/ricard/data/NMT-seq_EB/sample_sheet.csv"
io$outdir <- "/Users/ricard/NMT-seq_EB/dimensionality_reduction/out"

## Define options ##
opts <- list()

# Define which cells to use
opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T, sample]
# opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T & type=="NMT", sample]
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$metadata.file) %>% .[sample %in% opts$cells]
```

<!-- Load RNA expression data -->
```{r load_data, echo=FALSE}

# Load expression data and convert to data.table
sce <- readRDS(io$expr)
sce_filt <- sce[,opts$cells]
rna <- exprs(sce_filt) %>% t %>% as.data.table(keep.rownames = "sample") %>%
  melt(id.vars = "sample", value.name = "expr", variable.name = "gene") %>%
  merge(fData(sce_filt) %>% tibble::rownames_to_column("gene") %>% .[,c("gene","ens_id")] %>% setnames("ens_id","id")) %>%
  merge(sample_metadata, by="sample")

# Convert to matrtix
rna_matrix <- rna[,c("sample","gene","expr")] %>% dcast(sample~gene, value.var="expr") %>% matrix.please
```

<!-- t-SNE -->
```{r tsne, echo=FALSE}

## Using scater  ##
# tmp <- plotTSNE(sce_filt, ntop = 100, colour_by="type", return_SCESet=T)
# sce_filt$pluri <- tmp@reducedDimension[,2] > 5

# pdf(file="/Users/ricard/NMT-seq/rebuttal/EB/dimensionality_reduction/out/rna_tsne.pdf", useDingbats = F)
plotTSNE(sce_filt, ntop = 100, colour_by="lineage", shape_by="type", rand_seed=100)
# dev.off()

## Manual ##

# Select top n more variable genes
keep_variable <- 100
rna_matrix_filt <- rna_matrix[,names(tail(sort(apply(rna_matrix,2,var)), n=keep_variable))]

# Select overdispersed genes
# keep_variable <- 500
# rna_matrix_filt <- rna_matrix[,rownames(head( fData(sce_filt)[order(fData(sce_filt)$bioVar, decreasing = T),], n=keep_variable))]

# Perform t-SNE
set.seed(42)
# tsne <- tsne::tsne(rna_matrix_filt) # Slow
tsne <- Rtsne::Rtsne(rna_matrix_filt, check_duplicates=FALSE, pca=TRUE, theta=0.5, dims=2, perplexity = floor(nrow(rna_matrix_filt)/5))

to.plot <- tsne$Y %>% as.data.table %>% .[,sample:=rownames(rna_matrix_filt)] %>%
    merge(sample_metadata,by="sample")

# pdf(paste0(io$outdir,"/rna_tsne.pdf"), width=7, height=5, useDingbats = F)
ggplot(to.plot, aes(x=V1,y=V2)) +
  geom_point(aes(color=lineage,shape=method), alpha=0.7, size=2.0) +
  labs(x="t-SNE Dimension 1", y="t-SNE Dimension 2") +
  scatter_theme() +
  guides(colour = guide_legend(override.aes = list(size=3)),
         shape = guide_legend(override.aes = list(size=3)))
  # ggrepel::geom_text_repel(aes(label=sample))
# dev.off()

# pdf(paste0(io$outdir,"/tsne_meth.pdf"))
# ggplot(to.plot, aes(x=V1,y=V2)) +
#   geom_point(aes(color=stage,shape=Methylation), alpha=0.7) +
#   labs(x="t-SNE Dimension 1", y="t-SNE Dimension 2") +
#   scale_shape_manual(values = c(1,16)) +
#   scatter_theme() +
#   guides(colour = guide_legend(override.aes = list(size=3)),
#          shape = guide_legend(override.aes = list(size=3)))
# dev.off()
```

<!-- Unsupervised: Principal Component Analysis -->
```{r echo=FALSE, include=TRUE}
# plotPCA(sce_filt, ntop=100, colour_by="lineage", shape="method")
plotPCA(sce_filt, ntop=100, colour_by="lineage", shape="type")
```

<!-- Supervised: marker genes -->

<!-- Load pluripotency genes -->
```{r}
pluri <- fread("grep -v ^# /Users/ricard/data/NMT-seq_EB/markers/Pluri.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
pluri <- c(pluri,c("Mylpf","Ooep","Mreg"))

```

<!-- Define gene markers -->
```{r}
genes <- c("Esrrb","Zfp42","Prtg","T")
```

<!-- Supervised PCA with marker genes -->
```{r}
# sce_filt_pluri <- sce_filt[pluri,]
# tmp <- plotPCA(sce_filt_pluri, ncomponents = 1, return_SCESet = T)
# sce_filt$test <- tmp@reducedDimension[,"PC1"] < -1.5
# sce_filt$test <- -tmp@reducedDimension[,"PC1"] 
# plotTSNE(sce_filt, ntop=250, colour_by="test")
```

<!-- Supervised t-SNE with marker genes -->
```{r}

setkey(rna,gene)

p_list <- list()
for (gene in genes) {
  sce_filt$gene <- exprs(sce_filt)[gene,]
  # pdf(paste0(io$outdir,"/rna_",gene,"_tsne.pdf"), width=7, height=5, useDingbats = F)
  # plotTSNE(sce_filt, ntop=100, colour_by=gene, main=gene) %>% print
  
  set.seed(42)
  
  # Select top n more variable genes
  keep_variable <- 100
  rna_matrix_filt <- rna_matrix[,names(tail(sort(apply(rna_matrix,2,var)), n=keep_variable))]
  
  # Perform t-SNE
  tsne <- Rtsne::Rtsne(rna_matrix_filt, check_duplicates=FALSE, pca=TRUE, theta=0.5, dims=2, perplexity = floor(nrow(rna_matrix_filt)/5))
  
  # Generate plot
  to.plot <- tsne$Y %>% as.data.table %>% .[,sample:=rownames(rna_matrix_filt)] %>%
    merge(sample_metadata,by="sample") %>%
    merge(rna[gene,c("sample","expr")], by="sample")
  
  p_list[[gene]] <- ggplot(to.plot, aes(x=V1, y=V2)) +
    ggtitle(gene) +
    geom_point(aes(color=expr), alpha=0.7, size=2.0) +
    labs(x="t-SNE Dimension 1", y="t-SNE Dimension 2") +
    scale_colour_gradientn(name="Expression", colours = c("grey","red")) +
    scatter_theme() +
    theme(
      plot.title = element_text(size=rel(1.5), color="black"),
      axis.title.x = element_text(size=rel(1.1), color="black"),
      axis.title.y = element_text(size=rel(1.1), color="black"),
      axis.text.x = element_text(size=rel(1.0), color="black"),
      axis.text.y = element_text(size=rel(1.0), color="black"),
      legend.title = element_text(size=rel(1.1), color="black"),
      legend.text  = element_text(size=rel(1.1), color="black")
    )
  # pdf(paste0(io$outdir,"/rna_",gene,"_tsne.pdf"), width=7, height=5, useDingbats = F)
  # print(p_list[[gene]])
  # dev.off()
}

p <- cowplot::plot_grid(p_list[["Esrrb"]], p_list[["Zfp42"]], p_list[["T"]], p_list[["Prtg"]], ncol=2, nrow=2)
pdf(paste0(io$outdir,"/rna_supervised.pdf"), width=9, height=7, useDingbats = F)
print(p)
dev.off()
```

