---
title: "NMT-seq EB: dimensionality reduction using ZIFA"
author: "Ricard Argelaguet"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
```

```{r funcs, echo=FALSE}
# scatter_theme <- function() {
#   p <- theme(
#     plot.title = element_text(size=20, hjust=0.5),
#     axis.title.y = element_text(colour="black", size=20, margin=margin(0,15,0,0)),
#     axis.title.x = element_text(colour="black", size=20, margin=margin(15,0,0,0)),
#     axis.text.x = element_text(colour="black",size=rel(1.6)),
#     axis.text.y = element_text(colour="black",size=rel(1.6)),
#     axis.line = element_line(colour="black", size=rel(0.9)),
#     axis.ticks = element_line(colour="black", size=rel(1.0)),
#     panel.background = element_blank(),
#     panel.grid = element_blank(),
#     legend.position="right",
#     legend.text=element_text(size=15),
#     legend.key = element_blank(),
#     legend.title=element_text(size=17),
#     # legend.background=element_blank()
#     # panel.border = element_blank()
#   )
# }
```


```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$expr <- "/Users/ricard/data/NMT-seq_EB/rna/parsed/sceset.rds"
# io$metadata.file <- "/Users/ricard/data/NMT-seq_EB/sample_sheet_rna.csv"
io$metadata.file <- "/Users/ricard/data/NMT-seq_EB/sample_sheet.csv"
io$outdir <- "/Users/ricard/NMT-seq/rebuttal/EB/dimensionality_reduction/out"

## Define options ##
opts <- list()

# Define which cells to use
opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T, sample]
```

<!-- Load sample metadata -->
```{r load_metadata} 
sample_metadata <- fread(io$metadata.file) %>% .[sample %in% opts$cells] %>% .[,c("sample","lineage")]
```

<!-- Load expression data -->
```{r load_data, echo=FALSE}
sce <- readRDS(io$expr)[,sample_metadata$sample]
```

<!-- Filter the expression data -->
```{r filter, echo=FALSE}
sce_filt <- sce

# Filter genes based on dropout
opts$max.dropout <- 0.25
genes_dropout <- rownames(sce)[fData(sce)$pct_dropout<(opts$max.dropout*100)]
sce_filt <- sce_filt[genes_dropout,]

# Filter genes based on variance
# opts$fvar <- 0.1
# genes_var <- names(tail(sort(apply(exprs(sce_filt),1,var)), n=nrow(sce_filt)*opts$fvar))
# sce_filt <- sce_filt[genes_var,]
 
# Filter genes based on biological overdispersion
# opts$fvar <- 0.5
# genes_var <- rownames(sce_filt)[tail(sort(fData(sce_filt)$bioVar, index.return=TRUE)$ix, n=nrow(sce_filt)*opts$fvar)]
# sce_filt <- sce_filt[genes_var,opts$cells]
genes_oversdispersion <- rownames(sce_filt)[fData(sce_filt)$bioVar > 2.5]
sce_filt <- sce_filt[genes_oversdispersion,]

```

<!-- Save expression matrix and run ZIFA using Python -->
```{r}
write.table(round(exprs(sce_filt),3), file = "/Users/ricard/NMT-seq/rebuttal/EB/dimensionality_reduction/out/expr.csv", quote = F, sep = ",", row.names = TRUE, col.names = TRUE)
```

<!-- Load ZIFA results -->
```{r}
ZIFA <- fread("/Users/ricard/NMT-seq/rebuttal/EB/dimensionality_reduction/out/ZIFA.txt")
ZIFA[,sample:=colnames(sce_filt)] 
ZIFA <- ZIFA %>% merge(sample_metadata,by="sample")

p <- ggplot(ZIFA, aes(x=V1, y=V2)) +
  geom_point(aes(color=lineage), size=2.5) +
  theme_bw() + 
  labs(x="ZIFA dimension 1", y="ZIFA dimension 2") +
  theme(
    axis.title.y = element_text(colour="black", size=20, margin=margin(0,5,0,0)),
    axis.title.x = element_text(colour="black", size=20, margin=margin(5,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.6)),
    axis.text.y = element_text(colour="black",size=rel(1.6)),
    axis.ticks = element_line(colour="black", size=rel(1.3)),
    legend.position="right",
    legend.text=element_text(size=10),
    legend.key = element_blank(),
    legend.title=element_text(size=15)
    # legend.background=element_blank()
    # panel.border = element_blank()
  )
print(p)


# pdf("/Users/ricard/NMT-seq/dimensionality_reduction/out/ZIFA_out_12.pdf", width = 9, height = 6.5, useDingbats = F)
# print(p)
# dev.off()

```

<!-- Plot dimensionality reduction and color by expression of marker genes -->
```{r}
pluri <- fread("grep -v ^# /Users/ricard/data/NMT-seq_EB/markers/Pluri.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
diff <- c("Mylpf","Ooep","Mreg") # This come sfrom differnetial expression analysis
genes <- c(pluri,diff)
```
### PCA
```{r}
# sce_filt_pluri <- sce_filt[pluri,]
# tmp <- plotPCA(sce_filt_pluri, ncomponents = 1, return_SCESet = T)
# sce_filt$test <- tmp@reducedDimension[,"PC1"] < -1.5
# sce_filt$test <- -tmp@reducedDimension[,"PC1"] 
# plotTSNE(sce_filt, ntop=250, colour_by="test")
```
### t-SNE
```{r}

setkey(rna,gene)

p_list <- list()
for (gene in pluri) {
  sce_filt$gene <- exprs(sce_filt)[gene,]
  # pdf(paste0(io$outdir,"/rna_",gene,"_tsne.pdf"), width=7, height=5, useDingbats = F)
  # plotTSNE(sce_filt, ntop=100, colour_by=gene, main=gene) %>% print
  
  set.seed(42)
  
  # Select top n more variable genes
  keep_variable <- 100
  rna_matrix_filt <- rna_matrix[,names(tail(sort(apply(rna_matrix,2,var)), n=keep_variable))]
  
  # Perform t-SNE
  tsne <- Rtsne::Rtsne(rna_matrix_filt, check_duplicates=FALSE, pca=TRUE, theta=0.5, dims=2, perplexity = floor(nrow(rna_matrix_filt)/5))
  
  # Generate plot
  to.plot <- tsne$Y %>% as.data.table %>% .[,sample:=rownames(rna_matrix_filt)] %>%
    merge(sample_metadata,by="sample") %>%
    merge(rna[gene,c("sample","expr")], by="sample")
  
  # pdf(paste0(io$outdir,"/rna_",gene,"_tsne.pdf"), width=7, height=5, useDingbats = F)
  p_list[[gene]] <- ggplot(to.plot, aes(x=V1, y=V2)) +
    ggtitle(gene) +
    geom_point(aes(color=expr), alpha=0.7, size=2.0) +
    labs(x="t-SNE Dimension 1", y="t-SNE Dimension 2") +
    scale_colour_gradientn(name="Expression", colours = c("grey","red")) +
    scatter_theme() +
    theme(
      plot.title = element_text(size=rel(1.6), color="black"),
      axis.title.x = element_text(size=rel(1.4), color="black"),
      axis.title.y = element_text(size=rel(1.4), color="black"),
      axis.text.x = element_text(size=rel(1.5), color="black"),
      axis.text.y = element_text(size=rel(1.5), color="black"),
      legend.title = element_text(size=rel(1.3), color="black"),
      legend.text  = element_text(size=rel(1.2), color="black")
    )
  print(p_list[[gene]])
  # dev.off()
}

p <- cowplot::plot_grid(p_list[["Esrrb"]], p_list[["Zfp42"]], p_list[["Mreg"]], p_list[["Mylpf"]], ncol=2, nrow=2)
# pdf(paste0(io$outdir,"/rna_allgenes_tsne.pdf"), width=9, height=7, useDingbats = F)
print(p)
# dev.off()
```
