---
title: "NMT-Seq: Association between Acc conservation and pseudotime"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(BPRMeth))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(weights))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(truncnorm))
suppressPackageStartupMessages(library(MASS))
```

```{r echo=FALSE, include=FALSE}
gg_volcano_plot <- function(cor_samples, title = ""){
  p <- ggplot(cor_samples, aes(x=rho_spearman, y=-log10(p_spearman))) +
    labs(title=title, x="Spearman's rank correlation coefficient", y=expression(paste("-log"[10],"(",plain(p),")"))) +
    #geom_hline(yintercept = -log10(opts$threshold_fdr), color="blue") +
    geom_segment(aes(x=0, xend=0, y=0, yend=4.17), color="orange") +
    geom_point(aes(color=sig), size=2) +
    scale_color_manual(values=c("black","red")) +
    scale_x_continuous(limits=c(-.8, .8)) +
    scale_y_continuous(limits=c(0,4.3)) +
    annotate("text", x=0, y=4.29, size=7, label=sprintf("(%d)", all)) +
    annotate("text", x=-0.5, y=4.29, size=7, label=sprintf("%d (-)",length(negative_hits))) +
    annotate("text", x=0.5, y=4.29, size=7, label=sprintf("%d (+)",length(positive_hits))) +
    # geom_text(data=cor_samples[sig == TRUE], aes(x=r, y=log_padj_fdr, label=gene), vjust=-0.0, hjust=-0.3) +
    #ggrepel::geom_text_repel(data=cor_samples[sig == TRUE], aes(x=rho_spearman, y=-log10(p_spearman), label=gene), size=6) +
    ggrepel::geom_text_repel(data=cor_samples[1:5], aes(x=rho_spearman, y=-log10(p_spearman), label=gene), size=6) +
    scatter_volc_theme()
} 

ggplot_bpr_profiles <- function(X, obs, title="", subtitle="", up_label="-500bp", down_label="+500bp", middle_label="TSS", ...){
  # ggplot(X, aes(x = xs, y = ys)) +
  p <- ggplot(data = data.frame(X), aes(x = xs, y = ys)) +
    geom_line(aes(x = xs, y = ys), size=1.5, col = "darkblue") +
    geom_point(data = obs, mapping = aes(x = x, y = y), shape=1, color="red", size=3) +
    geom_ribbon(data = data.frame(X), mapping = aes(ymin= ys_low, ymax= ys_high), alpha=0.25, size = 0.1, fill="cornflowerblue") +
    scale_x_continuous(limits = c(-1, 1), labels =c(up_label, "", middle_label, "", down_label)) + 
    scale_y_continuous(limits = c(0, 1), breaks=pretty_breaks(n=4)) + 
    labs(title = title, subtitle = subtitle, x="genomic region", y="Accessibility") + 
    line_theme()# + theme(axis.text.x = element_blank())
}

# Define ggplot2 theme for scatter plots
scatter_theme <- function(){
  p <- theme(
      plot.title=element_text(size=28, face='bold', margin=margin(0,0,10,0), hjust=0.5),
      plot.subtitle = element_text(size=20, face='bold', margin=margin(0,0,10,0), hjust=0.5),
      axis.text=element_text(size=rel(1.75), color='black'),
      axis.title=element_text(size=rel(1.95), color='black'),
      axis.title.y = element_text(margin=margin(0,10,0,0)),
      axis.title.x = element_text(margin=margin(10,0,0,0)),
      legend.position="right",
      panel.border=element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank()
    )
}

# Define ggplot2 theme for scatter plots
scatter_volc_theme <- function(){
  p <- theme(
      plot.title=element_text(size=20, face='bold', margin=margin(0,0,10,0), hjust=0.5),
      axis.text=element_text(size=rel(1.5), color='black'),
      axis.title=element_text(size=rel(1.5), color='black'),
      axis.title.y = element_text(margin=margin(0,10,0,0)),
      axis.title.x = element_text(margin=margin(10,0,0,0)),
      legend.position="none",
      panel.border=element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank()
    )
}

# Scatter plot function
scatter_plot <- function(data, xlabel="", ylabel="", title="", subtitle="", lm=FALSE, loess = FALSE) {
  p <- ggplot(data, aes_string(x=names(data)[1], y=names(data)[2], col=names(data)[3])) +
    labs(x=xlabel, y=ylabel, title=title, subtitle=subtitle) +
    geom_point(shape = 16, size = 2.5, show.legend = FALSE, alpha = .55) + 
    scatter_theme() + 
    scale_color_gradient(low = "#0091ff", high = "#f0650e")
  if (lm){
    if (loess){ p <- p + geom_smooth() }#+ scale_x_continuous(trans = "log1p")
    else{ p <- p + geom_smooth(method='lm') }
  }
}

# Define ggplot2 boxplot theme for boxplots
boxplot_theme <- function() {
  p <- theme(
    plot.title = element_text(size=30, hjust=0.5, margin=margin(0,0,20,0)),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.title.x = element_text(colour="black", size=20, vjust=1.5, margin=margin(15,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.6)),
    axis.text.y = element_text(colour="black",size=rel(1.6)),
    axis.line = element_line(colour="black", size=rel(0.7)),
    axis.ticks.x = element_line(colour="black", size=rel(0.8)),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.position="none",
    legend.text=element_text(size=15),
    legend.title=element_blank(),
    legend.background=element_blank(),
    panel.border = element_blank()
  )
}

# Define ggplot2 boxplot theme for boxplots
barplot_theme <- function() {
  p <- theme(
    plot.title = element_text(size=30, hjust=0.5, margin=margin(0,0,20,0)),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.title.x = element_text(colour="black", size=20, vjust=1.5, margin=margin(15,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.6)),
    axis.text.y = element_text(colour="black",size=rel(1.6)),
    axis.line = element_line(colour="black", size=rel(0.7)),
    axis.ticks.x = element_line(colour="black", size=rel(0.8)),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.position="right",
    legend.text=element_text(size=13),
    legend.title=element_text(size=18),
    legend.background=element_blank(),
    panel.border = element_blank()
  )
}

# Define ggplot2 boxplot theme for boxplots
barplot_multi_theme <- function() {
  p <- theme(
    plot.title = element_text(size=30, hjust=0.5, margin=margin(0,0,20,0)),
    axis.title.y = element_text(colour="black", size=20, vjust=1.5),
    axis.title.x = element_text(colour="black", size=20, vjust=1.5, margin=margin(15,0,0,0)),
    axis.text.x = element_text(colour="black",size=rel(1.2)),
    axis.text.y = element_text(colour="black",size=rel(1.5)),
    axis.line = element_line(colour="black", size=rel(0.7)),
    axis.ticks.x = element_line(colour="black", size=rel(0.8)),
    axis.ticks.y = element_blank(),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    legend.position="right",
    legend.text=element_text(size=13),
    legend.title=element_text(size=18),
    legend.background=element_blank(),
    panel.border = element_blank()
  )
}

# Define ggplot2 theme for line plots
line_theme <- function(){
  p <- theme(
      plot.title=element_text(size=25, face='bold', margin=margin(0,0,5,0), hjust=0.5),
      axis.text=element_text(size=rel(1.15), color='black'),
      axis.title=element_text(size=rel(1.55), color='black'),
      axis.title.y = element_text(margin=margin(0,15,0,0)),
      axis.title.x = element_text(margin=margin(15,0,0,0)),
      axis.ticks.x = element_line(colour="black", size=rel(0.8)),
      axis.ticks.y = element_blank(),
      legend.position="right",
      legend.key.size = unit(1.9, 'lines'),
      legend.title=element_text(size=24, face='bold'),
      legend.text=element_text(size=19),
      panel.border=element_blank(),
      panel.grid.major = element_line(colour = "gainsboro"),
      #panel.grid.minor = element_line(colour = "grey"),
      panel.background = element_blank()
    )
}
```

<!-- # Parse and filter data -->
```{r echo=FALSE, include=FALSE}
# Data
io                     <- list()
io$base_dir            <- "/home/cakapourani/Documents/Code/datasets/nmt-seq-data-eb"
io$out_dir             <- "/home/cakapourani/Documents/Code/nmt-seq/rebuttal/EB/lineage_profiles/out/"
io$rna_file            <- paste0(io$base_dir, "/rna/parsed/sceset.rds")
io$acc_file            <- paste0(io$base_dir, "/acc/parsed/profiles/cons_cluster_prom_200_200_basis13_GpCcov10_bic2_cellcov0.6.rds")
io$genelist_dir        <- paste0(io$base_dir, "/metadata")
io$pseudotime          <- "/home/cakapourani/Documents/Code/nmt-seq/rebuttal/EB/pseudotime/out/destiny.tsv"

opts                   <- list()
opts$annos             <- c("prom_200_200")
opts$min.s             <- 20      # minimum number of samples to do the correlation
opts$threshold_fdr     <- 0.10    # qvalue threshold for significance in FDR
opts$threshold_p       <- 0.01    # qvalue threshold for significance in FDR
```

<!-- # Load scRNA data -->
```{r load_rna, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Load expression as SCESet object
sceset        <- readRDS(file = io$rna_file)
# Create data.table
rna_dt        <- exprs(sceset) %>% t %>% as.data.table(keep.rownames = "sample") %>% melt(id.vars = "sample", value.name = "expr", variable.name = "gene")
# Compute summary statistics for each gene across cells
rna_all_stats <- rna_dt[, .(mean_expr = mean(expr), median_expr = median(expr), var_expr = var(expr), sd_expr = sd(expr), cv_expr = sd(expr)/mean(expr)), by = gene]
N_cells       <- length(unique(rna_dt$sample))  # Number of unique cells
rna_all_stats <- rna_all_stats[, cv_expr := log2((1 + 1/(4 * N_cells)) * cv_expr)]  # Correct CV empirically
# Extract biological variance, i.e. overdispersion
rna_all_stats <- rna_all_stats[, overdispersion := fData(sceset)$bioVar]
# Extract gene coordinates metadata to do the overlap
rna_metadata  <- fData(sceset) %>% tibble::rownames_to_column("gene") %>% as.data.table %>% .[,c("chr", "start", "end", "gene", "ens_id")]  %>% .[, chr := as.factor(sub("chr", "", chr))] %>% setnames("ens_id", "id")
# Merge rna data with metadata
rna_all_stats <- merge(rna_metadata[, c("chr", "id", "gene")], rna_all_stats, by = c("gene")) # Merge using all samples
rna_dt        <- merge(rna_metadata[, c("chr", "id", "gene")], rna_dt, by = c("gene"))        # Merge using only samples that pass filtering

# Keep only variable genes
rna_all_stats <- rna_all_stats %>% .[mean_expr > 1]
rm(sceset, N_cells)
```

<!-- # Load acc profile data -->
```{r load_acc_prof, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Load accessibility data
acc_profile  <- readRDS(io$acc_file) %>% .[cells > opts$min.s] #%>% .[, rel_cov := coverage / cells] %>% .[rel_cov > 20]
# Make clusters column as factor and keep accessibility groups with more than 30 genes in each cluster
acc_profile <- acc_profile %>% .[, factor_clusters := factor(clusters)] %>% .[, N := .N, by = clusters] %>% .[N > 30]
# Merge with expression data using all samples 
accrna <- merge(rna_all_stats, acc_profile, by = c("id")) %>% setorder(clusters) 
rm(acc_profile)
```

<!-- # Load pseudotime data -->
```{r load_pseudotime, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
pseudotime <- fread(io$pseudotime , header=T ) %>% setorder(pseudotime)
```

<!-- # Load sc-NOMe-seq data -->
```{r load_acc, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Keep genes with more than one cluster
accrna <- accrna[clusters > 1]
p_spearman = rho_spearman = p_ordinal_reg = t_ordinal_reg <- vector(mode = "numeric", length = NROW(accrna))
# Get lineage agreement using Spearman rank test
for (i in 1:NROW(accrna)){
  # Get lineage assigment of each cell for specific gene
  cell_pseudotime <- pseudotime[sample %in% accrna$cell_names[[i]]]
  # Obtain the total number of cells
  N <- NROW(cell_pseudotime)
  # Get cluster assignments
  cell_clusters <- data.table(sample = accrna$cell_names[[i]], labels = accrna$cell_clusters[[i]]) %>% setkey(sample)
  cell_clusters <- cell_clusters[cell_pseudotime$sample]
  # Look only for genes with more than one cluster
  K <- length(unique(cell_clusters$labels))
  if (K > 1){
    # Copy data.table
    cl_obj <- copy(cell_clusters)
    # Iterate over each cluster k
    for (k in 1:K){
      # Get cluster lable of 1st instance
      lab1 <- cl_obj$labels[1]
      # get indices of cluster labels with cluster k
      ind_k <- which(cl_obj$labels == k)
      # If first element matches cluster k, don't do relabelling
      if (lab1 == k){
        cl_obj <- cl_obj[-ind_k]
      }else{
        # Which labels match label of 1st instance
        ind_lab1 <- which(cl_obj$labels == lab1)
        # Update them with the cluster label k
        cl_obj$labels[ind_lab1] <- k
        # The prevous labels with cluster k, relabel to the label of 1st instance
        cl_obj$labels[ind_k] <- lab1
        # Remove labels of 1st instance
        cl_obj <- cl_obj[-ind_lab1]
        
        # Do relabelling of all data
        act_ind_k <- which(cell_clusters$labels == k)
        act_lab1 <- which(cell_clusters$labels == lab1)
        # Update them with the cluster label k
        cell_clusters$labels[act_lab1] <- k
        # The prevous labels with cluster k, relabel to the label of 1st instance
        cell_clusters$labels[act_ind_k] <- lab1
      }
    }
    accrna$cell_names[[i]] <- cell_clusters$sample
    accrna$cell_clusters[[i]] <- cell_clusters$labels
    p_spearman[i] <- c(cor.test(cell_pseudotime$pseudotime, cell_clusters$labels, method = "spearman", exact = FALSE)$p.value)
    rho_spearman[i] <- cor(cell_pseudotime$pseudotime, cell_clusters$labels, method = "spearman")
    
    dt <- data.table(x = cell_pseudotime$pseudotime, y = as.factor(cell_clusters$labels))
    # test <- nnet::multinom(y ~ x, data = dt)
    # z <- summary(test)$coefficients/summary(test)$standard.errors
    # p <- (1 - pnorm(abs(z), 0, 1))*2
    
    if (K == 2){
      model <- glm(y ~ x, family=binomial(link='logit'), data=dt)
      ctable <- coef(summary(model))
      p_ordinal_reg[i] <- ctable[2, "Pr(>|z|)"]
      t_ordinal_reg[i] <- ctable[2, "z value"]
    }else{
      model <- polr(y ~ x, data = dt, Hess=TRUE)
      ctable <- coef(summary(model))
      p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
      ctable <- cbind(ctable, "p value" = p)
      p_ordinal_reg[i] <- ctable[1, "p value"]
      t_ordinal_reg[i] <- ctable[1, "t value"]
    }
  }else{
    p_spearman[i] <- 1
    rho_spearman[i] <- 0
    p_ordinal_reg[i] <- 1
    t_ordinal_reg[i] <- 0
  }
}
accrna <- accrna %>% .[, c("p_spearman", "rho_spearman", "p_ord_reg", "t_ord_reg") := list(p_spearman, rho_spearman, p_ordinal_reg, t_ordinal_reg)] %>% 
  .[, c("padj_fdr", "padj_bonf") := list(p.adjust(p_spearman, method = "fdr"), p.adjust(p_spearman, method = "bonferroni"))] %>%
  .[, c("log_padj_fdr","log_padj_bonf") := list(-log10(padj_fdr), -log10(padj_bonf))] %>%
  .[, sig_fdr := padj_fdr <= opts$threshold_fdr]  %>% .[, sig := p_spearman <= opts$threshold_p] %>% setorder(p_spearman)

rm(lab1, ind_k, ind_lab1, cl_obj, act_ind_k, act_lab1, p_spearman, rho_spearman, p_ordinal_reg, t_ordinal_reg, K, i, k, N, model, ctable, p)

accrna[1:50, c("gene", "p_spearman", "rho_spearman", "p_ord_reg", "t_ord_reg", "padj_fdr")]
#saveRDS(accrna, file = paste0(io$out_dir, "pseudotime_cor_filter.rds"))
```


<!-- Volcano plot of p-values against Pearson's r and QQ-plot of p-values -->
```{r plot_volcano, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE}
# Compute positive and negative hits in terms of correlation
negative_hits <- accrna[sig==TRUE & rho_spearman < 0, id]
positive_hits <- accrna[sig==TRUE & rho_spearman > 0, id]
all <- nrow(accrna)
    
p <- gg_volcano_plot(accrna, title = "")
print(p)

invisible(pdf(file=paste0(io$out_dir,"cluster-pseudotime-cor.pdf"), width = 10, height = 7, useDingbats = FALSE)); p; invisible(dev.off())
#grid.arrange(pp[[n]], qq[[n]], ncol=2, top = textGrob(n, gp=gpar(fontsize=29, fontface = "bold")), newpage = TRUE)
```


<!-- Volcano plot of p-values against Pearson's r and QQ-plot of p-values -->
```{r plot_profiles, eval=FALSE, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
load(paste0(io$base_dir,"/acc/parsed/profiles/acc_400bp.RData"))
io$out_dir <- "/home/cakapourani/Documents/Code/nmt-seq/rebuttal/EB/lineage_profiles/out/"

# Load cell metadata
metadata <- fread(io$meta_file) %>% .[,c("sample", "culture", "pass_metQC", "pass_accQC", "pass_rnaQC", "lineage")] %>% 
  na.omit() %>% .[pass_accQC ==  TRUE & pass_rnaQC == TRUE]
```


```{r ggg, eval=FALSE,echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
opts$top_N <- 5
for (hits in 1:opts$top_N){
  gene_id <- accrna$id[hits]                      # Get gene ENS id
  gene_dt <- lapply(region_dt, "[[", gene_id)     # Extract accessibility data
  cl_names <- accrna$cell_names[[hits]]           # Names of cells passed filtering
  cl_assign <- accrna$cell_clusters[[hits]]       # Cluster assignment of cells
  cl_profiles <- accrna$cell_profiles[[hits]]     # Learned profiles for each cluster
  K <- NCOL(cl_profiles)                          # Number of clusters K
  xs <- seq(-1, 1, length = 100)
  ys <- matrix(0, ncol = K, nrow = length(xs))
  labs <- vector("character", length = K)
  opts$basis_prof <- create_rbf_object(M = NROW(cl_profiles) - 1)
  for (k in 1:K){   # Iterate over each cluster
    ys[,k] <- eval_probit_function(opts$basis_prof, xs, cl_profiles[, k]) # Evaluate function for plotting
    nnn <- cl_names[which(cl_assign == k)]                                # Get names of cells belonging to each cluster
    labs[k] <- paste0("C", k, " ", round(median(rna_dt[id == gene_id & sample %in% nnn]$expr), 2))
  }
  # Create a data.table object
  dt2 <- data.table(ys) %>% setnames(labs) %>% melt(variable.name = "Cluster", value.name = "ys") %>% .[, xs := xs]
  # Create plot of cluesters
  p_cl_prof <- ggplot(dt2, aes(x = xs, y = ys, color=Cluster)) + geom_line(size=2) +
      scale_x_continuous(limits = c(-1, 1), labels =c("-200bp", "", "TSS", "", "+200bp")) + 
      scale_y_continuous(limits = c(0, 1), breaks=pretty_breaks(n=4)) + 
      scale_color_brewer(palette="Dark2") + scale_fill_brewer(palette="Dark2") +
      labs(title = paste0("Gene ", accrna$gene[hits]), x="genomic region", y="Accessibility") + line_theme()
  
  # Create subdirectories for each gene
  io$out_dir_loc <- paste0(io$out_dir, "/pseudotime/", hits, "_", gene_id, "/")
  ifelse(!dir.exists(file.path(io$out_dir_loc)), dir.create(file.path(io$out_dir_loc)), FALSE)
  
  gene_dt_filt <- gene_dt[cl_names]
  prof_cells <- bpr_bayes(x = gene_dt_filt, basis = opts$basis_prof, gibbs_nsim = 3000, 
                            gibbs_burn_in = 1000, is_parallel = FALSE, keep_gibbs_draws = TRUE)
  cells_names <- names(gene_dt_filt)
  H <- design_matrix(x = opts$basis_prof, obs = xs)$H  # Create design matrix
  ys_draws <- matrix(0, nrow = NROW(prof_cells$W_draws[[1]]), ncol = length(xs))
  dt <- data.table(xs = xs, ys = 0, ys_low = 0, ys_high = 0)
  pp <- list()
  for (m in 1:length(cl_names)){
    w_draws <- prof_cells$W_draws[[m]] # Compute predictive distribution
    for (i in 1:NROW(prof_cells$W_draws[[1]])){ ys_draws[i, ] <- pnorm(H %*% w_draws[i, ]) }
    # Compute quantiles of ys
    ys_q <- apply(ys_draws, 2, quantile, probs = c(0.1, 0.9),  na.rm = TRUE)
    dt <- dt %>% .[, c("ys", "ys_low", "ys_high") := list(colMeans(ys_draws), ys_q[1, ], ys_q[2, ])]
    obs <- as.data.table(gene_dt_filt[[m]]) %>% setnames(c("x", "y"))
    pp[[m]] <- ggplot_bpr_profiles(X = dt, obs = obs, title = paste0("Cell ", cells_names[m]), subtitle = paste0("Expr = ", round(rna_dt[id == gene_id & sample == cells_names[m], expr], 3)),  up_label = "-200bp", down_label = "+200bp", middle_label = "TSS")
    
    pdf(file = paste0(io$out_dir_loc, "t", m, "_K", cl_assign[m], "_", metadata[sample == cells_names[m]]$lineage, "_", cells_names[m], "_", gene_id, ".pdf"), width = 6, height = 4, useDingbats = FALSE)
    print(pp[[m]])
    dev.off()
  }
  
  pdf(file = paste0(io$out_dir_loc, "cl_profiles_", gene_id, ".pdf"), width = 6, height = 4, useDingbats = FALSE)
  print(p_cl_prof)
  dev.off()
}
```

# GO analysis
Here we perform Gene Ontology analysis to see whether specific clusters of genes are enriched for specific pathways.
```{r go_enr_list, echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, fig.height=6}
io$reactomeFile  <- paste0(io$genelist_dir, "/mouse_v75_reactome.rds")
io$reactomeFile2 <- paste0(io$genelist_dir, "/AllPathways.txt")

# Read reactome file and change gene names to Upper case
reactome           <- readRDS(io$reactomeFile); colnames(reactome) <- toupper(colnames(reactome))
# Read pathways file to change from ID to description pathway
tmp                <- read.table(io$reactomeFile2, header=F, quote="", sep="\t", stringsAsFactors=F)[,c(1,2)]
reactome_meta      <- tmp[,2]; names(reactome_meta) <- tmp[,1]
rownames(reactome) <- stringr::str_replace_all(rownames(reactome), reactome_meta)
feature.sets       <- reactome  # Store results to the following object
opts$min.size      <- 10  # Filter feature sets with small number of features
feature.sets       <- feature.sets[rowSums(feature.sets)>=opts$min.size, ]
# Remove features that do not intersect between the feature sets and the data
accrna_tmp        <- copy(accrna)
features          <- intersect(toupper(accrna_tmp$gene), colnames(feature.sets))
foo_filt          <- accrna_tmp[,gene := toupper(gene)] %>% .[gene %in% features]
feature.sets_filt <- feature.sets[,features]

# Melt and merge data to do the fisher's test
asd <- melt.data.table(as.data.table(feature.sets_filt, keep.rownames="pathway"), id.vars = "pathway", 
                       variable.name="gene", value.name="value") %>% merge(foo_filt[,c("gene", "sig")], allow.cartesian=T, by="gene")
# Get GO list for each cluster
go_list <- list()
iter_lab <- c(TRUE, FALSE)
for (c in 1:2) {
  go_list[[c]] <- asd[,.(p=fisher.test(x=matrix(data=c(.SD[sig==c & value==1,.N], .SD[sig!=c & value==1,.N],
                                                       .SD[sig==c & value==0,.N], .SD[sig!=c & value==0,.N]), 
                                                nrow=2, ncol=2), alternative="greater")[["p.value"]]), by="pathway"] %>% 
    .[,padj:=p.adjust(p, method = "fdr")] %>% setorder(p)
  # Create a nice formatted table
  # print(knitr::kable(go_list[[c]][1:45], caption = paste0("GO enrichment: Cluster ", c)))
  
  # Convert pvalues to log scale (add a small regulariser to avoid numerical errors)
  tmp <- copy(go_list[[c]])
  tmp$log <- -log10(tmp$padj)
  #order according to significance
  tmp$pathway <- factor(tmp$pathway, levels = tmp$pathway[order(tmp$padj, decreasing = T)])
  p <- ggplot(tmp[1:38], aes(x=pathway, y=log)) +
    geom_point(size=5) +
    geom_hline(yintercept=-log10(opts$threshold_fdr), linetype="longdash", color = "red") +
    scale_color_manual(values=c("black","red")) +
    geom_segment(aes(xend=pathway, yend=0)) +
    ylab(expression(paste("-log"[10],"(",plain(q),"-value)"))) + coord_flip() +
    theme(axis.text.y = element_text(size=rel(0.9), hjust=1, color='black'),
      axis.text.x = element_text(size=rel(1.2), vjust=0.5, color='black'),
      axis.title.y=element_blank(), legend.position='none',
      panel.background = element_blank()
    )
  print(p)
  invisible(pdf(file = paste0(io$out_dir, "GO_analysis/GO_enrichment_C", c, ".pdf"), width = 12, height = 10, useDingbats=FALSE)); print(p); invisible(dev.off())
  fwrite(go_list[[c]], file = paste0(io$out_dir, "GO_analysis/GO_enrichment_C", c, ".csv"))
}
saveRDS(go_list, file = paste0(io$out_dir, "GO_analysis/GO_list.rds"))
rm(reactome, reactome_meta, tmp, p, asd, features, foo_filt, feature.sets_filt, accrna_tmp, feature.sets, c)
```