---
title: "NMT-seq EB: heatmap of expression data"
author: "Ricard Argelaguet"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
```

```{r funcs, echo=FALSE}
matrix.please<-function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}
```


```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$expr <- "/Users/ricard/data/NMT-seq_EB/rna/parsed/sceset.rds"
io$metadata.file <- "/Users/ricard/data/NMT-seq_EB/sample_sheet.csv"
io$outdir <- "/Users/ricard/NMT-seq/rebuttal/EB/heatmap/out"

## Define options ##
opts <- list()

# Define which cells to use
opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T, sample]
# opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T & type=="NMT", sample]
```

```{r load_data, echo=FALSE}

# Load sample metadata
sample_metadata <- fread(io$metadata.file) %>% .[sample %in% opts$cells]

# Load expression data and convert to data.table
sce <- readRDS(io$expr)
# rna <- exprs(sce_filt) %>% t %>% as.data.table(keep.rownames = "sample") %>%
#   melt(id.vars = "sample", value.name = "expr", variable.name = "gene") %>%
#   merge(fData(sce_filt) %>% tibble::rownames_to_column("gene") %>% .[,c("gene","ens_id")] %>% setnames("ens_id","id")) %>%
#   merge(sample_metadata, by="sample")
```


```{r filter, echo=FALSE}

sce_filt <- sce[,opts$cells]

# Filter genes based on dropout
opts$max.dropout <- 0.25
genes_dropout <- rownames(sce)[fData(sce)$pct_dropout<(opts$max.dropout*100)]
sce_filt <- sce[genes_dropout,]

# Filter genes based on variance
# opts$fvar <- 0.25
# genes_var <- names(tail(sort(apply(exprs(sce_filt),1,var)), n=nrow(sce_filt)*opts$fvar))
# sce_filt <- sce_filt[genes_var,]
 
# Filter genes based on biological overdispersion

opts$fvar <- 0.25
genes_var <- rownames(sce_filt)[tail(sort(fData(sce_filt)$bioVar, index.return=TRUE)$ix, n=nrow(sce_filt)*opts$fvar)]
sce_filt <- sce_filt[genes_var,opts$cells]

# opts$fvar <- 0.5
# genes_oversdispersion <- rownames(sce_filt)[fData(sce_filt)$bioVar > 2];
# genes_oversdispersion <- genes_oversdispersion[!is.na(genes_oversdispersion)]
# sce_filt <- sce_filt[genes_oversdispersion,]

```

<!-- ```{r convert_dt2matrix, echo=FALSE} -->
<!-- rna_matrix <- rna[,c("sample","gene","expr")] %>% dcast(sample~gene, value.var="expr") %>% matrix.please -->
<!-- ``` -->

```{r heatmap, echo=FALSE}


# heatmap.2(t(exprs(sce_filt)), col=colorRampPalette(rev(brewer.pal(n = 7, name =
# "RdYlBu")))(100), na.color = "gray95", Rowv=T, Colv=T, density.info="none", trace="none",
#           key=T, labRow = FALSE, labCol = FALSE)

annotation_row <- sample_metadata[,c("sample","plate","type")] %>% as.data.frame %>%
  tibble::column_to_rownames("sample")

pheatmap::pheatmap(exprs(sce_filt),
                   cluster_rows = T, cluster_cols = T, annotation_row = NA, annotation_col = annotation_row,
                   show_colnames = F, show_rownames = F)

# pheatmap::pheatmap(exprs(sce_filt), kmeans_k = 100,
#                    cluster_rows = T, cluster_cols = T, annotation_row = NA, annotation_col = annotation_row,
#                    show_colnames = F, show_rownames = F)
```


## Marker genes
```{r load_genes, echo=FALSE}

pluri <- fread("grep -v ^# /Users/ricard/data/NMT-seq_EB/markers/Pluri.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]

pluri_denovo <- c("Ooep","Mylpf","Manba","Mreg")

pre <- fread("grep -v ^# /Users/ricard/data/NMT-seq_EB/markers/PrEn.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]

# housek <- fread("/Users/ricard/NMT-seq/genesets/housekeeping.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]

epi <- fread("grep -v ^# /Users/ricard/data/NMT-seq_EB/markers/Epi.tsv", header=F) %>% setnames(c("ens_id","gene")) %>% .[["gene"]]
```

### Heatmap
```{r, echo=FALSE, include=TRUE}

feature_df <- data.frame(gene=c(pluri,pluri_denovo), 
                         class=c(rep("Pluripotency known",length(pluri)),
                                 rep("Pluripotency de novo",length(pluri_denovo))
                                 # rep("Primitive Endoderm",length(pre)),
                                 # rep("Housekeeping",length(housek)),
                                 # rep("Epiblast",length(epi)))
                         )) %>% tibble::column_to_rownames("gene")

sample_df <- data.frame(sample=colnames(sce), type=sce$type, culture=sce$culture, lineage=sce$lineage) %>%
  tibble::column_to_rownames("sample")

# annotation_colors	<- list(culture=c("red","green"), type=c("blue","orange"), )

pheatmap::pheatmap(t(exprs(sce_filt)[rownames(feature_df),]), border_color="black", main="",
         cluster_cols=F, cluster_rows=T, show_rownames=F, show_colnames=T,
         annotation_row=sample_df, annotation_col=feature_df, annotation_colors=NA,
         legend=TRUE, annotation_legend=TRUE, legend_labels=NA,
         annotation_names_col=F, fontsize=13)
```
